# **E-commerce Sales Analysis** 

## Introduction
This notebook analyzes an e-commerce sales dataset using Python and Pandas.

The analysis focuses on understanding sales performance across different categories, cities, products, and payment methods. Various Pandas operations such as data selection, filtering, sorting, grouping, and aggregation are used to extract meaningful insights from the dataset.

### Objectives

- Load and explore the e-commerce sales dataset
- Select and filter relevant records
- Sort orders based on sales and quantity
- Analyze sales by category, city, product, and payment method
- Calculate important sales statistics
- Identify top-performing products and categories
- Generate meaningful observations from the analysis

In [3]:
import pandas as pd

df = pd.read_csv("Day8_Ecommerce_Sales_Dataset.csv")
df.head()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

## 1. Exploring the Dataset
Before performing analysis, it is important to understand the basic structure of the dataset.

In [6]:
df.tail()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking
98,1099,2026-03-06,Hiba Sheikh,Ahmedabad,West,Books,Machine Learning Basics,2,999,0,1998.00,3.8,UPI
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card

In [8]:
# Display five random records
df.sample(5, random_state=42)

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
83,1084,2026-06-19,Aisha Mir,Kolkata,East,Electronics,Wireless Mouse,5,899,10,4045.50,3.8,Cash on Delivery
53,1054,2026-04-22,Aisha Mir,Chennai,South,Home & Kitchen,Coffee Maker,1,3499,15,2974.15,4.3,Net Banking
70,1071,2026-01-16,Aditya Verma,Pune,West,Home & Kitchen,Water Bottle,4,699,10,2516.40,4.5,Net Banking
45,1046,2026-01-03,Ananya Singh,Delhi,North,Books,The Alchemist,4,499,15,1696.60,3.8,Credit Card
44,1045,2026-03-27,Reyansh Jain,Jammu,North,Books,Machine Learning Basics,1,999,0,999.00,4.0,Debit Card

In [10]:
# Check the shape of the dataset

print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Number of Rows: 100
Number of Columns: 13

In [12]:
# Display column names
print(df.columns.tolist())

['Order_ID', 'Order_Date', 'Customer', 'City', 'Region', 'Category', 'Product', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Total_Sales', 'Rating', 'Payment_Method']

In [14]:
# Display data types
print(df.dtypes)

Order_ID              int64
Order_Date           object
Customer             object
City                 object
Region               object
Category             object
Product              object
Quantity              int64
Unit_Price            int64
Discount_Percent      int64
Total_Sales         float64
Rating              float64
Payment_Method       object
dtype: object

In [16]:
# Display complete dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          100 non-null    int64
 1   Order_Date        100 non-null    object
 2   Customer          100 non-null    object
 3   City              100 non-null    object
 4   Region            100 non-null    object
 5   Category          100 non-null    object
 6   Product           100 non-null    object
 7   Quantity          100 non-null    int64
 8   Unit_Price        100 non-null    int64
 9   Discount_Percent  100 non-null    int64
 10  Total_Sales       100 non-null    float64
 11  Rating            100 non-null    float64
 12  Payment_Method    100 non-null    object
dtypes: float64(2), int64(4), object(7)
memory usage: 10.3+ KB

## 2. Data Selection
Pandas allows us to select specific columns and rows from a DataFrame. This is useful when we want to focus on particular aspects of the dataset.

In [20]:
df["Product"].head()

0    Wireless Headphones
1          Running Shoes
2             Power Bank
3    Mechanical Keyboard
4            Smart Watch
Name: Product, dtype: object

In [22]:
df[["Order_ID", "Product", "Category", "Total_Sales"]].head()

   Order_ID              Product     Category  Total_Sales
0      1001  Wireless Headphones  Electronics      4497.00
1      1002        Running Shoes       Sports      2799.00
2      1003           Power Bank  Electronics      2038.30
3      1004  Mechanical Keyboard  Electronics      9496.20
4      1005          Smart Watch  Electronics      3134.05

In [24]:
df.iloc[:5]

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

In [26]:
# Select specific columns and rows

df.loc[:4, ["Order_ID", "Customer", "Total_Sales"]]

   Order_ID      Customer  Total_Sales
0      1001     Kabir Ali      4497.00
1      1002  Aditya Verma      2799.00
2      1003    Sara Ahmed      2038.30
3      1004     Kabir Ali      9496.20
4      1005   Priya Menon      3134.05

## 3. Data Filtering
Filtering allows us to identify records that satisfy specific conditions.

In [31]:
# Orders with sales greater than ₹10,000

high_value_orders = df[df["Total_Sales"] > 10000]

high_value_orders[
    ["Order_ID", "Product", "City", "Total_Sales"]
]

    Order_ID        Product       City  Total_Sales
12      1013         Jacket    Lucknow     10620.75
47      1048   Coffee Maker    Lucknow     10497.00
48      1049  Running Shoes     Mumbai     13995.00
52      1053  Running Shoes  Hyderabad     13295.25
84      1085   Coffee Maker  Hyderabad     12596.40
89      1090    Cricket Bat    Lucknow     12495.00

In [33]:
# Orders belonging to the Sports category

sports_orders = df[df["Category"] == "Sports"]

sports_orders[
    ["Order_ID", "Product", "Total_Sales"]
]

    Order_ID        Product  Total_Sales
1       1002  Running Shoes      2799.00
11      1012    Cricket Bat      4498.20
13      1014  Running Shoes      8397.00
16      1017    Cricket Bat      7497.00
20      1021       Yoga Mat       809.10
22      1023       Football      2157.30
23      1024  Running Shoes      2799.00
24      1025       Football      3995.00
26      1027       Football      3395.75
30      1031       Yoga Mat       764.15
35      1036       Yoga Mat      1798.00
37      1038   Dumbbell Set      9495.25
39      1040   Dumbbell Set      1999.00
48      1049  Running Shoes     13995.00
52      1053  Running Shoes     13295.25
54      1055       Yoga Mat      3056.60
55      1056   Dumbbell Set      3798.10
58      1059    Cricket Bat      8496.60
59      1060   Dumbbell Set      5397.30
71      1072       Yoga Mat      4045.50
81      1082       Yoga Mat      2292.45
82      1083       Football       759.05
89      1090    Cricket Bat     12495.00
92      1093    Cricket Bat      8496.60
95      1096   Dumbbell Set      9495.25

In [35]:
# Orders paid using UPI
upi_orders = df[df["Payment_Method"] == "UPI"]

upi_orders[
    ["Order_ID", "Product", "Total_Sales"]
]

    Order_ID                  Product  Total_Sales
4       1005              Smart Watch      3134.05
10      1011             Coffee Maker      6998.00
13      1014            Running Shoes      8397.00
14      1015      Wireless Headphones      2998.00
15      1016            The Alchemist      1696.60
18      1019                   Jacket      7497.00
19      1020            Mixer Grinder      2999.00
23      1024            Running Shoes      2799.00
24      1025                 Football      3995.00
27      1028      Wireless Headphones      5696.20
29      1030       Python Programming      2996.00
31      1032            Atomic Habits      1078.20
33      1034                  T-Shirt      1598.00
36      1037               Power Bank      2038.30
38      1039            Mixer Grinder      5698.10
41      1042             Water Bottle      3495.00
43      1044                  T-Shirt      1518.10
46      1047           Wireless Mouse      3820.75
47      1048             Coffee Maker     10497.00
61      1062      Mechanical Keyboard      7497.00
63      1064            Atomic Habits      2396.00
68      1069           Wireless Mouse      1708.10
77      1078  Machine Learning Basics       899.10
86      1087            Atomic Habits      2036.60
96      1097                  T-Shirt       679.15
98      1099  Machine Learning Basics      1998.00

## 4. Sorting the Data
The `sort_values()` function is used to arrange records according to one or more columns.

In [40]:
# Top 10 orders by Total Sales
top_orders = df.sort_values(
    by="Total_Sales",
    ascending=False
)

top_orders[
    ["Order_ID", "Product", "Category", "City", "Total_Sales"]
].head(10)

    Order_ID              Product        Category        City  Total_Sales
48      1049        Running Shoes          Sports      Mumbai     13995.00
52      1053        Running Shoes          Sports   Hyderabad     13295.25
84      1085         Coffee Maker  Home & Kitchen   Hyderabad     12596.40
89      1090          Cricket Bat          Sports     Lucknow     12495.00
12      1013               Jacket        Clothing     Lucknow     10620.75
47      1048         Coffee Maker  Home & Kitchen     Lucknow     10497.00
69      1070               Jacket        Clothing       Delhi      9996.00
79      1080               Jacket        Clothing       Delhi      9996.00
3       1004  Mechanical Keyboard     Electronics     Lucknow      9496.20
51      1052  Mechanical Keyboard     Electronics  Chandigarh      9496.20

## 5. Overall Sales Analysis
The following calculations provide an overview of the overall performance of the e-commerce dataset.

In [43]:
total_sales = df["Total_Sales"].sum()
average_sales = df["Total_Sales"].mean()
highest_sales = df["Total_Sales"].max()
lowest_sales = df["Total_Sales"].min()
total_quantity = df["Quantity"].sum()
number_of_orders = df["Order_ID"].nunique()

print(f"Total Sales       : ₹{total_sales:,.2f}")
print(f"Average Sales     : ₹{average_sales:,.2f}")
print(f"Highest Sale      : ₹{highest_sales:,.2f}")
print(f"Lowest Sale       : ₹{lowest_sales:,.2f}")
print(f"Total Quantity    : {total_quantity}")
print(f"Number of Orders  : {number_of_orders}")

Total Sales       : ₹447,262.95
Average Sales     : ₹4,472.63
Highest Sale      : ₹13,995.00
Lowest Sale       : ₹449.10
Total Quantity    : 294
Number of Orders  : 100

## 6. Category-wise Sales Analysis
The `groupby()` function is used to analyze sales performance across different product categories.

In [46]:
category_analysis = df.groupby("Category").agg(
    Orders=("Order_ID", "count"),
    Total_Sales=("Total_Sales", "sum"),
    Average_Sales=("Total_Sales", "mean"),
    Quantity_Sold=("Quantity", "sum")
).sort_values(
    by="Total_Sales",
    ascending=False
)

category_analysis

                Orders  Total_Sales  Average_Sales  Quantity_Sold
Category
Sports              25    136026.45    5441.058000             79
Home & Kitchen      21    113329.90    5396.661905             59
Electronics         19     92086.00    4846.631579             57
Clothing            14     69028.20    4930.585714             39
Books               21     36792.40    1752.019048             60

In [49]:
## 7. City-wise Sales Analysis

In [51]:
city_analysis = df.groupby("City").agg(
    Orders=("Order_ID", "count"),
    Total_Sales=("Total_Sales", "sum"),
    Average_Sales=("Total_Sales", "mean"),
    Quantity_Sold=("Quantity", "sum")
).sort_values(
    by="Total_Sales",
    ascending=False
)

city_analysis

             Orders  Total_Sales  Average_Sales  Quantity_Sold
City
Hyderabad         7     59076.45    8439.492857             25
Chennai          10     47493.20    4749.320000             29
Lucknow           6     46194.65    7699.108333             22
Pune             10     41908.55    4190.855000             34
Mumbai            8     41457.80    5182.225000             23
Kochi             9     37257.50    4139.722222             29
Chandigarh        8     34539.65    4317.456250             22
Delhi             6     30882.80    5147.133333             18
Jaipur            7     25534.00    3647.714286             17
Kolkata           7     20169.00    2881.285714             24
Jammu             6     16059.75    2676.625000             11
Ahmedabad         6     14788.70    2464.783333             12
Bengaluru         4     13524.30    3381.075000             14
Srinagar          5     11778.60    2355.720000             12
Bhubaneswar       1      6598.00    6598.000000              2

## 7. Product-wise Sales Analysis

In [54]:
product_analysis = df.groupby("Product").agg(
    Orders=("Order_ID", "count"),
    Total_Sales=("Total_Sales", "sum"),
    Average_Sales=("Total_Sales", "mean"),
    Quantity_Sold=("Quantity", "sum")
).sort_values(
    by="Total_Sales",
    ascending=False
)

product_analysis

                         Orders  Total_Sales  Average_Sales  Quantity_Sold
Product
Coffee Maker                  7     51610.25    7372.892857             16
Jacket                        5     47106.15    9421.230000             20
Cricket Bat                   5     41483.40    8296.680000             18
Running Shoes                 5     41285.25    8257.050000             15
Wireless Headphones           7     33877.40    4839.628571             23
Dumbbell Set                  5     30184.90    6036.980000             16
Mechanical Keyboard           3     26489.40    8829.800000             11
Electric Kettle               5     26382.40    5276.480000             19
Mixer Grinder                 4     25341.55    6335.387500              9
Smart Watch                   3     15670.25    5223.416667              5
Yoga Mat                      6     12765.80    2127.633333             16
Atomic Habits                 6     11590.65    1931.775000             21
Football                      4     10307.10    2576.775000             14
Water Bottle                  5      9995.70    1999.140000             15
Wireless Mouse                3      9574.35    3191.450000             12
T-Shirt                       5      7790.25    1558.050000             10
Hoodie                        2      7675.20    3837.600000              5
Python Programming            4      7527.45    1881.862500             11
The Alchemist                 6      7485.00    1247.500000             17
Power Bank                    3      6474.60    2158.200000              6
Jeans                         2      6456.60    3228.300000              4
Machine Learning Basics       4      5694.30    1423.575000              6
Data Science Handbook         1      4495.00    4495.000000              5

## 8. Payment Analysis

In [57]:
payment_analysis = df.groupby("Payment_Method").agg(
    Orders=("Order_ID", "count"),
    Total_Sales=("Total_Sales", "sum"),
    Average_Sales=("Total_Sales", "mean"),
    Quantity_Sold=("Quantity", "sum")
).sort_values(
    by="Total_Sales",
    ascending=False
)

payment_analysis

                  Orders  Total_Sales  Average_Sales  Quantity_Sold
Payment_Method
Credit Card           22    106540.25    4842.738636             65
Debit Card            20     98064.90    4903.245000             64
Net Banking           17     96371.25    5668.897059             63
UPI                   26     96163.25    3698.586538             70
Cash on Delivery      15     50123.30    3341.553333             32

## 9. Top performing Products

In [60]:
top_products = product_analysis.head(5)

print("Top 5 Products by Total Sales:")
top_products

Top 5 Products by Total Sales:

                     Orders  Total_Sales  Average_Sales  Quantity_Sold
Product
Coffee Maker              7     51610.25    7372.892857             16
Jacket                    5     47106.15    9421.230000             20
Cricket Bat               5     41483.40    8296.680000             18
Running Shoes             5     41285.25    8257.050000             15
Wireless Headphones       7     33877.40    4839.628571             23

## 10. Top performing Categories

In [63]:
top_categories = category_analysis.sort_values(
    by="Total_Sales",
    ascending=False
)

print("Categories Ranked by Total Sales:")
top_categories

Categories Ranked by Total Sales:

                Orders  Total_Sales  Average_Sales  Quantity_Sold
Category
Sports              25    136026.45    5441.058000             79
Home & Kitchen      21    113329.90    5396.661905             59
Electronics         19     92086.00    4846.631579             57
Clothing            14     69028.20    4930.585714             39
Books               21     36792.40    1752.019048             60

## 11. Conclusion

This analysis demonstrated how Python and Pandas can be used to analyze e-commerce sales data.

Data selection, filtering, sorting, grouping, and aggregation were used to examine sales across categories, cities, products, and payment methods. Overall sales statistics were also calculated to understand the performance of the dataset.

The analysis identified Sports as the leading category, Hyderabad as the highest-selling city, and Coffee Maker as the top-performing product by total sales. Payment-method analysis also showed differences in order volume and sales performance.

These techniques provide a foundation for more advanced sales analysis and data visualization.